services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    hostname: "app"
    networks:
      - frontend
      - backend
    volumes:
      # - /etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default:ro
      - /etc/letsencrypt/live/picovpn.ru/fullchain.pem:/etc/letsencrypt/live/picovpn.ru/fullchain.pem:ro
      - /etc/letsencrypt/live/picovpn.ru/privkey.pem:/etc/letsencrypt/live/picovpn.ru/privkey.pem:ro
      # - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      # - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off;'
networks:
  frontend:
    external: true
  backend:
    external: false