services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    hostname: "app"
    networks:
      - frontend
      - backend
networks:
  frontend:
    external: true
  backend:
    external: false